# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-19 06:13+0000\n"
"PO-Revision-Date: 2014-11-14 17:01+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/nova/language/"
"ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: nova/api/openstack/__init__.py:101
#, python-format
msgid "%(url)s returned with HTTP %(status)d"
msgstr "HTTP %(status)d の %(url)s が返されました"

#: nova/api/openstack/__init__.py:298
msgid "V3 API has been disabled by configuration"
msgstr ""

#: nova/api/openstack/wsgi.py:665
#, python-format
msgid "Fault thrown: %s"
msgstr "障害がスローされました: %s"

#: nova/api/openstack/wsgi.py:668
#, python-format
msgid "HTTP exception thrown: %s"
msgstr "HTTP 例外がスローされました: %s"

#: nova/compute/manager.py:2555
msgid "Instance is already powered off in the hypervisor when stop is called."
msgstr ""

#: nova/compute/manager.py:2832
#, python-format
msgid "bringing vm to original state: '%s'"
msgstr "VM を元の状態に戻しています: '%s'"

#: nova/compute/manager.py:5760
#, python-format
msgid ""
"During sync_power_state the instance has a pending task (%(task)s). Skip."
msgstr ""

#: nova/db/sqlalchemy/api.py:3295
#, python-format
msgid ""
"quota_usages out of sync, updating. project_id: %(project_id)s, user_id: "
"%(user_id)s, resource: %(res)s, tracked usage: %(tracked_use)s, actual "
"usage: %(in_use)s"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:36
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:36
msgid ""
"Skipped adding reservations_deleted_expire_idx because an equivalent index "
"already exists."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/234_add_expire_reservations_index.py:58
#: nova/db/sqlalchemy/migrate_repo/versions/248_add_expire_reservations_index.py:58
msgid ""
"Skipped removing reservations_deleted_expire_idx because index does not "
"exist."
msgstr ""

#: nova/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr "Eventlet backdoorは、プロセス%(pid)dの%(port)sをリスニングしています。"

#: nova/openstack/common/periodic_task.py:126
#, python-format
msgid "Skipping periodic task %(task)s because its interval is negative"
msgstr "タスクの間隔が負であるため、定期タスク %(task)s をスキップしています"

#: nova/openstack/common/periodic_task.py:131
#, python-format
msgid "Skipping periodic task %(task)s because it is disabled"
msgstr "タスクが使用不可であるため、定期タスク %(task)s をスキップしています"

#: nova/openstack/common/service.py:174
#, python-format
msgid "Caught %s, exiting"
msgstr "%s が見つかりました。終了しています"

#: nova/openstack/common/service.py:232
msgid "Parent process has died unexpectedly, exiting"
msgstr "親プロセスが予期せずに停止しました。終了しています"

#: nova/openstack/common/service.py:263
#, python-format
msgid "Child caught %s, exiting"
msgstr ""

#: nova/openstack/common/service.py:302
msgid "Forking too fast, sleeping"
msgstr "fork が早すぎます。スリープ状態にしています"

#: nova/openstack/common/service.py:321
#, python-format
msgid "Started child %d"
msgstr "子 %d を開始しました"

#: nova/openstack/common/service.py:331
#, python-format
msgid "Starting %d workers"
msgstr "%d ワーカーを開始しています"

#: nova/openstack/common/service.py:348
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr "子 %(pid)d がシグナル %(sig)d によって強制終了されました"

#: nova/openstack/common/service.py:352
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr "子 %(pid)s が状況 %(code)d で終了しました"

#: nova/openstack/common/service.py:391
#, python-format
msgid "Caught %s, stopping children"
msgstr "%s が見つかりました。子を停止しています"

#: nova/openstack/common/service.py:400
msgid "Wait called after thread killed.  Cleaning up."
msgstr ""

#: nova/openstack/common/service.py:416
#, python-format
msgid "Waiting on %d children to exit"
msgstr "%d 個の子で終了を待機しています"

#: nova/scheduler/client/report.py:52
#, python-format
msgid "Compute_service record updated for %s"
msgstr ""

#: nova/scheduler/filters/utils.py:50
#, python-format
msgid "%(num_values)d values found, of which the minimum value will be used."
msgstr ""

#: nova/virt/block_device.py:222
#, python-format
msgid "preserve multipath_id %s"
msgstr ""

#: nova/virt/firewall.py:444
#, python-format
msgid "instance chain %s disappeared during refresh, skipping"
msgstr ""

#: nova/virt/disk/vfs/api.py:67
msgid "Unable to import guestfsfalling back to VFSLocalFS"
msgstr ""

#: nova/virt/hyperv/vmops.py:447
msgid "Soft shutdown succeeded."
msgstr ""

#: nova/virt/libvirt/driver.py:953
#, python-format
msgid ""
"Unable to use bulk domain list APIs, falling back to slow code path: %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1065
msgid "Instance destroyed successfully."
msgstr "インスタンスが正常に破棄されました。"

#: nova/virt/libvirt/driver.py:1075
msgid "Instance may be started again."
msgstr "インスタンスを再び開始できます。"

#: nova/virt/libvirt/driver.py:1085
msgid "Going to destroy instance again."
msgstr "インスタンスの破棄を再び行います。"

#: nova/virt/libvirt/driver.py:1728
msgid "Beginning live snapshot process"
msgstr "ライブ・スナップショット・プロセスを開始しています"

#: nova/virt/libvirt/driver.py:1731
msgid "Beginning cold snapshot process"
msgstr "コールド・スナップショット・プロセスを開始しています"

#: nova/virt/libvirt/driver.py:1761
msgid "Snapshot extracted, beginning image upload"
msgstr ""
"スナップショットが抽出されました。イメージのアップロードを開始しています"

#: nova/virt/libvirt/driver.py:1773
msgid "Snapshot image upload complete"
msgstr "スナップショット・イメージのアップロードが完了しました"

#: nova/virt/libvirt/driver.py:2283
msgid "Instance soft rebooted successfully."
msgstr "インスタンスが正常にソフト・リブートされました。"

#: nova/virt/libvirt/driver.py:2326
msgid "Instance shutdown successfully."
msgstr "インスタンスが正常にシャットダウンされました。"

#: nova/virt/libvirt/driver.py:2334
msgid "Instance may have been rebooted during soft reboot, so return now."
msgstr ""
"インスタンスはソフト・リブート時にリブートされた可能性があるため、ここで返し"
"ます。"

#: nova/virt/libvirt/driver.py:2403
msgid "Instance rebooted successfully."
msgstr "インスタンスが正常にリブートされました。"

#: nova/virt/libvirt/driver.py:2446
msgid "Instance already shutdown."
msgstr ""

#: nova/virt/libvirt/driver.py:2462
#, python-format
msgid "Instance shutdown successfully after %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2491
#, python-format
msgid "Instance failed to shutdown in %d seconds."
msgstr ""

#: nova/virt/libvirt/driver.py:2649
msgid "Instance spawned successfully."
msgstr "インスタンスが正常に作成されました。"

#: nova/virt/libvirt/driver.py:2665
#, python-format
msgid "data: %(data)r, fpath: %(fpath)r"
msgstr "データ: %(data)r, ファイルパス: %(fpath)r"

#: nova/virt/libvirt/driver.py:2704 nova/virt/libvirt/driver.py:2731
#, python-format
msgid "Truncated console log returned, %d bytes ignored"
msgstr ""
"切り捨てられたコンソール・ログが返されました。%d バイトが無視されました"

#: nova/virt/libvirt/driver.py:2962
msgid "Creating image"
msgstr "イメージの作成中"

#: nova/virt/libvirt/driver.py:3090
msgid "Using config drive"
msgstr "構成ドライブを使用中"

#: nova/virt/libvirt/driver.py:3099
#, python-format
msgid "Creating config drive at %(path)s"
msgstr "構成ドライブを %(path)s に作成しています"

#: nova/virt/libvirt/driver.py:4064
msgid "Configuring timezone for windows instance to localtime"
msgstr ""

#: nova/virt/libvirt/driver.py:4950
#, python-format
msgid ""
"Getting block stats failed, device might have been detached. Instance="
"%(instance_name)s Disk=%(disk)s Code=%(errcode)s Error=%(e)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4956
#, python-format
msgid ""
"Could not find domain in libvirt for instance %s. Cannot get block stats for "
"device"
msgstr ""
"インスタンス %s 用のドメインが Libvirt 内で見つかりませんでした。デバイスのブ"
"ロックの統計を取得できません"

#: nova/virt/libvirt/driver.py:5257
#, python-format
msgid "Instance launched has CPU info: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6045
msgid "Instance running successfully."
msgstr "インスタンスが正常に実行されています。"

#: nova/virt/libvirt/driver.py:6399
#, python-format
msgid "Deleting instance files %s"
msgstr ""

#: nova/virt/libvirt/driver.py:6412
#, python-format
msgid "Deletion of %s failed"
msgstr ""

#: nova/virt/libvirt/driver.py:6416
#, python-format
msgid "Deletion of %s complete"
msgstr ""

#: nova/virt/libvirt/firewall.py:108
msgid "Called setup_basic_filtering in nwfilter"
msgstr "nwfilter で setup_basic_filtering を呼び出しました"

#: nova/virt/libvirt/firewall.py:116
msgid "Ensuring static filters"
msgstr "静的フィルターの確認中"

#: nova/virt/libvirt/firewall.py:326
msgid "Attempted to unfilter instance which is not filtered"
msgstr ""
"フィルター処理されていないインスタンスに対してフィルター処理の取り消しが試み"
"られました"

#: nova/virt/libvirt/imagebackend.py:363
#, python-format
msgid "Failed to get image info from path %(path)s; error: %(error)s"
msgstr ""

#: nova/virt/libvirt/imagecache.py:190
#, python-format
msgid "Writing stored info to %s"
msgstr "保管された情報を %s に書き込んでいます"

#: nova/virt/libvirt/imagecache.py:400
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): image verification skipped, no hash stored"
msgstr ""
"(%(base_file)s) にあるイメージ %(id)s: イメージの検査がスキップされました。"
"ハッシュは保管されていません"

#: nova/virt/libvirt/imagecache.py:409
#, python-format
msgid "%(id)s (%(base_file)s): generating checksum"
msgstr "%(id)s (%(base_file)s): チェックサムの生成中"

#: nova/virt/libvirt/imagecache.py:437
#, python-format
msgid "Base file too young to remove: %s"
msgstr "基本ファイルは新しいため削除できません: %s"

#: nova/virt/libvirt/imagecache.py:440
#, python-format
msgid "Removing base file: %s"
msgstr "基本ファイルを削除しています: %s"

#: nova/virt/libvirt/imagecache.py:458
#, python-format
msgid "image %(id)s at (%(base_file)s): checking"
msgstr "(%(base_file)s) にあるイメージ %(id)s: 検査中"

#: nova/virt/libvirt/imagecache.py:482
#, python-format
msgid ""
"image %(id)s at (%(base_file)s): in use: on this node %(local)d local, "
"%(remote)d on other nodes sharing this instance storage"
msgstr ""
"(%(base_file)s) にあるイメージ %(id)s: 使用中: このノード上では %(local)d "
"ローカル、このインスタンスのストレージを共有する他のノード上では %(remote)d"

#: nova/virt/libvirt/imagecache.py:549
#, python-format
msgid "Active base files: %s"
msgstr "アクティブな基本ファイル: %s"

#: nova/virt/libvirt/imagecache.py:552
#, python-format
msgid "Corrupt base files: %s"
msgstr "破損した基本ファイル: %s"

#: nova/virt/libvirt/imagecache.py:556
#, python-format
msgid "Removable base files: %s"
msgstr "削除可能な基本ファイル: %s"

#: nova/virt/libvirt/utils.py:513
msgid "findmnt tool is not installed"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:340
#, python-format
msgid "Mountpoint %(mountpoint)s attached to vmdk instance %(instance_name)s"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:375
#, python-format
msgid "Mountpoint %(mountpoint)s attached to iscsi instance %(instance_name)s"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:515
#, python-format
msgid "Mountpoint %(mountpoint)s detached from vmdk instance %(instance_name)s"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:544
#, python-format
msgid ""
"Mountpoint %(mountpoint)s detached from iscsi instance %(instance_name)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:684
#, python-format
msgid "Deleted %s snapshots."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1327
#, python-format
msgid ""
"Image creation data, cacheable: %(cache)s, downloaded: %(downloaded)s "
"duration: %(duration).2f secs for image %(image_id)s"
msgstr ""
